language: ruby

rvm:
  - 1.9.3
  - 2.2

gemfile:
  - gemfiles/rails_3.2_stable.gemfile
  - gemfiles/rails_4.0_stable.gemfile
  - gemfiles/rails_4.1_stable.gemfile
  - gemfiles/rails_4.2_stable.gemfile

matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails_3.2.13.gemfile

script: 'xvfb-run bundle exec rspec'
