language: ruby

rvm:
  - 1.9.3
  - 2.2

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/3.2.gemfile

script: 'xvfb-run bundle exec rspec'

notifications:
  email: false

addons:
  code_climate:
    repo_token: 6c87590be3659336b31ddbe14ca02841dc8afd8324fde8f37d451970abe5d787
